import Head from "next/head";
import Image from "next/image";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum,
          veniam delectus maiores, nihil culpa ex, repellendus repellat
          molestiae autem alias itaque velit aperiam aliquid quisquam? A saepe
          veritatis atque culpa.
        </p>
      </main>
    </>
  );
};

export default Home;
